### ISSUE TITLE
why I run this code but no respo

### ISSUE THREAD

**Issue by ChengJunJunJun** [Roywangj/AdaptPoint#2]

**Comment by ChengJunJunJun** [comment]
# install cpp extensions, the pointnet++ library
cd openpoints/cpp/pointnet2_batch
python setup.py install
cd ../

**Comment by Roywangj** [comment]
hi @ChengJunJunJun. When you run ---python setup.py install---, does it show some errors? If not, it shows that it compiles correctly.

**Comment by ChengJunJunJun** [comment]
我运行这个程序之后，这个程序不会结束，我不能继续输命令了

**Comment by ChengJunJunJun** [comment]
<img width="846" alt="截屏2023-10-12 22 32 32" src="https://github.com/Roywangj/AdaptPoint/assets/127819698/6c74fa2f-f16f-4b2c-bf21-5bcc244e0207">
就是这样，然后就没有反应了

**Comment by Roywangj** [comment]
does it start compile, or it failes?  You can also try ---python setup.py develop---. Besides, please delete the '/build' folder

你好，请问你输入之后，有任何输出吗，还是就卡在这里了。另外，你可以尝试以下python setup.py develop。 注意，在重复编译前，请删除之前编译得到的 ‘./build’文件夹。

**Comment by Roywangj** [comment]
hi @ChengJunJunJun , does  ---python setup.py develop--- works?

**Comment by ChengJunJunJun** [comment]
我现在试一下

**Comment by ChengJunJunJun** [comment]
<img width="996" alt="截屏2023-10-13 11 11 42" src="https://github.com/Roywangj/AdaptPoint/assets/127819698/2c22d2df-2211-430e-b478-0c8f96fb91c6">
还是没有反应

**Comment by Roywangj** [comment]
It seems strange. Maybe you can create a new env and try again. It should have some output, whether it succeed or fail. By the way,  can you describe the cuda and torch you used?

**Comment by ChengJunJunJun** [comment]
我刚刚换了一个服务器，问题解决了
