### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by ChengJunJunJun** [Roywangj/AdaptPoint#3]
<img width="829" alt="image" src="https://github.com/Roywangj/AdaptPoint/assets/127819698/25162413-6ad3-4b1e-a5a3-8458781a9437">
但是现在有这个问题

**Comment by ChengJunJunJun** [comment]
<img width="868" alt="截屏2023-10-13 14 18 13" src="https://github.com/Roywangj/AdaptPoint/assets/127819698/e093db16-059e-4631-ae81-d277caa86e84">
不能够导入chamfer

**Comment by Roywangj** [comment]
Hi, do you complile the 'chamfer_dist' cpp, just as the 
`cd chamfer_dist, 
python setup.py install,
cd ../emd,
python setup.py install,
cd ../../../`

**Comment by ChengJunJunJun** [comment]
谢谢，我现在已经解决了
